# -*- coding: utf-8 -*-
"""Week1_Budget_Tracker_Lisa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14bXTShMHBGzzrz5WxHQLgU4IrJATL7ww

# Mini Project 01: AI-Powered Budget Tracker
# ISYS2001 Introduction to Business Programming

**Instructions:**
1. Save a copy of this notebook to your Google Drive (File > Save a copy in Drive)  
2. Rename it to include your name: `Week1_Budget_Tracker_[YourName]`  
3. Complete all sections and code cells  
4. Document your AI interactions as you go

## Part 1: Environment Setup and First Steps
"""

# Run this cell to test your environment
print("🎉 Welcome to ISYS2001: Introduction to Business Programming!")
print("📊 Project: Personal Finance Assistant")
print("🤖 Today's Goal: Build a Simple Budget Tracker with AI Help")

# Import datetime to timestamp your work
from datetime import datetime
print(f"\n📅 Worksheet started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

"""## Part 2: Your First AI Prompt

Use an AI assistant (Gemini in Colab, ChatGPT, or GitHub Copilot) to create a program that:
- Asks the user for their name
- Asks for their monthly income  
- Prints a personalized welcome message

### 📝 Document Your AI Prompt Below:
"""

# TASK: Write your AI prompt as a comment below
"""
My AI Prompt:
[Replace this with the actual prompt you used with your AI assistant]
"""

# Paste the AI-generated code below:
# [YOUR AI-GENERATED CODE GOES HERE]

"""### 🔍 Evidence Package Entry #1"""

# Evidence Package Documentation
evidence_1 = {
    "timestamp": datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    "context": "I wanted to create a simple input/output program to practice AI prompting",
    "ai_tool_used": "Gemini/ChatGPT/Copilot",  # Update this
    "what_worked": "The AI understood my request and...",
    "what_didnt": "I had to clarify...",
    "what_i_learned": "I learned that specific prompts..."
}

# Display your evidence
print("📋 EVIDENCE PACKAGE #1")
for key, value in evidence_1.items():
    print(f"{key}: {value}")

"""## Part 3: Building the Budget Tracker

Use AI to help you write a program that:
- Allows users to input their monthly income
- Allows users to input up to 3 expenses  
- Calculates remaining budget
- Shows a warning if budget is negative

### 💡 Pro Tip: Be specific about requirements!
"""

# TASK: Write your detailed prompt for the budget tracker
"""
My Budget Tracker Prompt:
[Write your detailed prompt here]
"""

"""### Paste and Test Your AI-Generated Budget Tracker"""

# AI-GENERATED BUDGET TRACKER CODE
# [Paste your code here]

"""### 🐛 Debugging and Refinement"""

# Document any issues and fixes
issues_found = [
    "Issue 1: [Describe the problem]",
    "Fix 1: [How you solved it]",
    # Add more as needed
]

print("🔧 DEBUGGING NOTES:")
for item in issues_found:
    print(f"- {item}")

# REFINED VERSION - Your Working Budget Tracker
# [Paste your corrected/improved code here]

"""## Part 4: Enhancement Challenge

Choose ONE feature to add using AI assistance:
- 🏷️ Expense categories (food, transport, entertainment)
- 📊 Show percentage of income spent
- ✅ Input validation (no negative numbers)
- 📝 Detailed budget summary with advice
"""

# Document your enhancement
enhancement_choice = "I chose to add: [your choice]"
enhancement_prompt = """
[Write the prompt you used to add this feature]
"""

print(f"🚀 ENHANCEMENT: {enhancement_choice}")

# ENHANCED BUDGET TRACKER
# [Paste your enhanced code here]

"""## Part 5: Reflection and Lab Exit Ticket Preparation"""

from datetime import datetime

# Final Evidence Package Summary
evidence_2 = {
    "timestamp": datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    "context": "Creating the full budget tracker with enhancements",
    "ai_tool_used": "Gemini",
    "prompts_used": 5,  # Update this number
    "iterations_needed": 2,  # How many times you refined
    "final_reflection": "I learned how to start coding with the help of AI when I was struggling at the beginning"
}

print("📋 EVIDENCE PACKAGE #2 (Final)")
for key, value in evidence_2.items():
    print(f"{key}: {value}")

"""## 🎯 Submission Checklist

Before submitting:
- ✅ All code cells run without errors
- ✅ You've documented at least 2 AI interactions  
- ✅ Budget tracker accepts income and 3+ expenses
- ✅ Completed both Evidence Packages
- ✅ Attempted the enhancement challenge
- ✅ Reflected on your AI collaboration experience
"""

# Generate submission summary
print("="*50)
print("WEEK 1 WORKSHEET COMPLETION SUMMARY")
print("="*50)
print(f"Student Name: [Your Name]")
print(f"Completion Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print("\nCore Features Implemented:")
print("✅ Basic income/expense input")
print("✅ Budget calculation")
print("✅ Warning for negative budget")
print("✅ Enhancement: [Your enhancement]")
print("\nAI Collaboration Stats:")
print(f"- AI tools used: [List them]")
print(f"- Number of prompts: [Count]")
print(f"- Success rate: [Estimate]%")
print("\n🎉 Ready for Lab Exit Ticket submission!")

"""## 💭 Final Reflection Questions

**1. What surprised you most about working with AI to generate code?**  
[Your answer here]

**2. What makes a good prompt vs. a poor prompt?**  
[Your answer here]

**3. How do you see AI tools fitting into your future programming workflow?**  
[Your answer here]

---

### 📁 Save and Next Steps:
1. File > Save a copy in GitHub (if you haven't already)    
2. Prepare evidence for next lab session for the Exit Ticket  
3. Start thinking about Week 2: Variables & Data Types!

"""

